common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('dust_checker', include('dust_checker.urls')),
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dust_checker/urls.py
from django.urls import path
from . import views

app_name = 'dust_checker'

urlpatterns = [
    path('', views.index, name='index'),
    path('/detail', views.detail, name='detail'),
]

common/models.py
from django.db import models

# Create your models here.

dust_checker/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main.html')

dust_checker/views.py
from django.shortcuts import render
from .api import check_air

def index(request):
    res = check_air()
    pm10 = res.get('다사읍')
    context = {'station': '다사읍', 'pm10': pm10}
    return render(request, 'dust_checker/dust_main.html', context)

def detail(request):
    res = check_air()
    context = {'dust': res}
    return render(request, 'dust_checker/dust_detail.html', context)

templates/dust_checker/dust_detail.html
{% extends 'main.html' %}
{% block content %}
<!-- ---------------------- [edit] ------------------------ -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<div class="row justify-content-center mb-2">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    {% for key in dust.keys %}
                        <th scope="col">{{key}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for value in dust.values %}
                        <td>{{value}}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex justify-content-center mb-2">
    <div class="col-md-6">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script>
var label = new Array();
var data = new Array();
{% for key, value in dust.items %}
    label.push('{{key}}');
    data.push('{{value}}');
{% endfor %}


var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: label,
        datasets: [{
            label: '미세먼지 수치',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: data
        }]
    },

    // Configuration options go here
    options: {}
});
</script>
<!-- -------------------------------------------------------- -->
{% endblock %}

templates/dust_checker/dust_main.html
{% extends 'main.html' %}
{% block content %}
<div class="row justify-content-center mb-2">
    <div class="col-md-4">
        <div class="card" >
            <img src="/static/images/dust.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">미세먼지 수치</h5>
                <p class="card-text">{{pm10}}</p>
                <a href="{% url 'dust_checker:detail'%}" class="btn btn-primary">>> 자세히</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">HELPER</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dust_checker:index' %}">미세먼지</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>My Website</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- 웹 페이지의 내용 -->

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>